# Generated by Django 3.2.7 on 2021-10-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('blood_group', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=15)),
                ('place', models.CharField(max_length=50)),
            ],
        ),
    ]
